name: Deploy to Azure Functions

on:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_NAME: func-iajxc4x24u3aw
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: computacion-nube

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
